# Generated by Django 3.2 on 2021-04-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210410_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_disclosed', 'Not Disclosed')], default='male', max_length=13),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='premium_member',
            field=models.BooleanField(default=False),
        ),
    ]
