# Generated by Django 3.2 on 2021-04-24 11:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserDetails',
        ),
    ]
