# Generated by Django 3.2 on 2021-04-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_userprofile_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='bio',
            field=models.TextField(blank=True, default='Let others know about you...'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
