# Generated by Django 3.2 on 2021-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userdetails_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='received_hearts',
            field=models.IntegerField(default=0),
        ),
    ]
