# Generated by Django 3.2 on 2021-05-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userdetails_received_hearts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='daily_given_hearts',
            field=models.IntegerField(default=0),
        ),
    ]
