# Generated by Django 3.2 on 2021-05-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_2_4'),
        ('users', '0014_userdetails_daily_given_hearts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription'),
        ),
    ]
