# Generated by Django 3.2.3 on 2021-05-19 19:41

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_userdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='nationality',
            field=django_countries.fields.CountryField(default='Where are you from?', max_length=2),
        ),
    ]
