# Generated by Django 3.2.3 on 2021-05-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_userdetails_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='bio',
            field=models.TextField(blank=True, default='Let others know about you...', max_length=900),
        ),
    ]
