# Generated by Django 3.2 on 2021-04-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpost',
            old_name='content',
            new_name='new_post',
        ),
    ]
