# Generated by Django 3.2 on 2021-04-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0002_rename_content_addpost_new_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpost',
            old_name='author',
            new_name='user',
        ),
    ]
