# Generated by Django 3.2 on 2021-04-24 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profilepage', '0003_rename_author_addpost_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addPost',
            new_name='Post',
        ),
    ]
