# Generated by Django 3.2 on 2021-05-06 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profilepage', '0006_friendlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friend_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
