# Generated by Django 3.2 on 2021-05-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0007_alter_friendlist_friend_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='friendlist',
        ),
    ]
