# Generated by Django 3.2.3 on 2021-05-22 21:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profilepage', '0009_hearts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hearts',
            new_name='Heart',
        ),
    ]
